### ISSUE TITLE
SUM not working with any other AR methods on master

### ISSUE THREAD

**Issue by SixiS** [thiagopradi/octopus#497]
This is working in `0.9.2` but broken on `master`.

If you try use the ActiveRecord `sum` after any other clauses it breaks.
Just using `sum` works fine.

Example test:
```ruby
    it 'sum' do
      u = User.using(:brazil).create!(:name => 'Teste', :number => 11)
      v = User.using(:master).create!(:name => 'Teste', :number => 12)

      # Working
      expect(User.using(:master).sum(:number)).to eq(12)
      expect(User.using(:brazil).sum(:number)).to eq(11)
      expect(User.where(id: v.id).sum(:number)).to eq(12)

      # Broken
      expect(User.using(:brazil).where(id: u.id).sum(:number)).to eq(11)
      expect(User.using(:master).where(id: v.id).sum(:number)).to eq(12)
    end
```

The above generates this error:
```
     NoMethodError:
       undefined method `+' for :number:Symbol
     # ./lib/octopus/relation_proxy.rb:32:in `public_send'
     # ./lib/octopus/relation_proxy.rb:32:in `method_missing'
     # ./lib/octopus/scope_proxy.rb:47:in `block in method_missing'
     # ./lib/octopus/proxy.rb:86:in `block (2 levels) in run_queries_on_shard'
     # ./lib/octopus/proxy.rb:326:in `using_shard'
     # ./lib/octopus/proxy.rb:85:in `block in run_queries_on_shard'
     # ./lib/octopus/proxy.rb:310:in `keeping_connection_proxy'
     # ./lib/octopus/proxy.rb:84:in `run_queries_on_shard'
     # ./lib/octopus/shard_tracking.rb:31:in `run_on_shard'
     # ./lib/octopus/scope_proxy.rb:47:in `method_missing'
     # ./spec/octopus/model_spec.rb:404:in `block (3 levels) in <top (required)>'
```

Fix: https://github.com/thiagopradi/octopus/pull/498

**Comment by SixiS** [comment]
@thiagopradi @sekiyama58 

Looks like it was this commit:
https://github.com/thiagopradi/octopus/commit/404cbfc085cfec5bba304f57633602322dfe9de3#diff-e38f48d68535e19667f0d49d0026734eR25

`sum` should be an ENUM_WITH_BLOCK method?
https://github.com/thiagopradi/octopus/pull/498

**Comment by sekiyama58** [comment]
Thanks to pointing out this. It seems I was misunderstanding something about specification of sum method.

To use ActiveRecord's sum method, :sum should be completely removed from ENUM_METHODS explicitly, like:

```
    ENUM_METHODS = (::Enumerable.instance_methods - ::Object.instance_methods).reject do |m|
      ::ActiveRecord::Relation.instance_method(m).source_location rescue nil
    end + [:each, :map, :index_by] - [:sum]
```

In addition, all the test for sum in spec/octopus/association_shard_tracking_spec.rb should be changed from

```
... .sum(&:id)
```

to

```
... .sum(:id)
```

**Comment by pboling** [comment]
For reference, this was the fix: https://github.com/thiagopradi/octopus/pull/498
