### ISSUE TITLE
Rails 5.1: Gem Load Error - undefined method `alias_method_chain' for ActiveRecord

### ISSUE THREAD

**Issue by giangstrider** [thiagopradi/octopus#441]
Hi guys, I guess Octopus have problem with Rails 5.1?
After install gem and config shards.yml
```
octopus:
  replicated: true
  fully_replicated: true
  verify_connection: true
  environments:
    - development
  development:
    shard_one:
      adapter: mysql2
      encoding: utf8
      database: 
      pool: 5
      username: root
      password:
      host:
      port: 3306
```
I got this problem:
```
Bundler::GemRequireError: There was an error while trying to load the gem 'ar-octopus'.
Gem Load Error is: undefined method `alias_method_chain' for ActiveRecord::Base:Class
Did you mean?  alias_method
Backtrace for gem load error is:
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.1.2/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ar-octopus-0.9.0/lib/octopus/model.rb:48:in `included'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ar-octopus-0.9.0/lib/octopus/model.rb:7:in `include'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ar-octopus-0.9.0/lib/octopus/model.rb:7:in `extended'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ar-octopus-0.9.0/lib/octopus/model.rb:208:in `extend'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ar-octopus-0.9.0/lib/octopus/model.rb:208:in `<top (required)>'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ar-octopus-0.9.0/lib/octopus.rb:169:in `require'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ar-octopus-0.9.0/lib/octopus.rb:169:in `<top (required)>'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ar-octopus-0.9.0/lib/ar-octopus.rb:1:in `require'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ar-octopus-0.9.0/lib/ar-octopus.rb:1:in `<top (required)>'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/Users/x/app/ruby-facebook-crawler/config/application.rb:17:in `<top (required)>'
/Users/x/app/ruby-facebook-crawler/Rakefile:4:in `require_relative'
/Users/x/app/ruby-facebook-crawler/Rakefile:4:in `<top (required)>'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/Users/x/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/x/.rbenv/versions/2.4.0/bin/rake:22:in `load'
/Users/x/.rbenv/versions/2.4.0/bin/rake:22:in `<main>'
Bundler Error Backtrace:
/Users/x/app/ruby-facebook-crawler/config/application.rb:17:in `<top (required)>'
/Users/x/app/ruby-facebook-crawler/Rakefile:4:in `require_relative'
/Users/x/app/ruby-facebook-crawler/Rakefile:4:in `<top (required)>'
NoMethodError: undefined method `alias_method_chain' for ActiveRecord::Base:Class
Did you mean?  alias_method
/Users/x/app/ruby-facebook-crawler/config/application.rb:17:in `<top (required)>'
/Users/x/app/ruby-facebook-crawler/Rakefile:4:in `require_relative'
/Users/x/app/ruby-facebook-crawler/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```
Anyway to fix it?
Thanks guy

**Comment by thiagopradi** [comment]
Can you try to use Octopus 0.9.1? It should work with Rails 5.1. Please reopen this issue if this problem still appears after updating the gem. 

Thiago
