### ISSUE TITLE
Octopus is unusable with Rails 3.2.11

### ISSUE THREAD

**Issue by idlecool** [thiagopradi/octopus#152]
Octopus doesnt seem to work with Rails 3.2.11

```
% rake db:octopus --trace
rake aborted!
undefined method `announce' for class `Class'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.11/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.11/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method_chain'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/ar-octopus-0.3.4/lib/octopus/migration.rb:9:in `singletonclass'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/ar-octopus-0.3.4/lib/octopus/migration.rb:3:in `extended'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/ar-octopus-0.3.4/lib/octopus/migration.rb:73:in `extend'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/ar-octopus-0.3.4/lib/octopus/migration.rb:73:in `<top (required)>'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/ar-octopus-0.3.4/lib/octopus.rb:66:in `<top (required)>'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `require'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `each'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `block in require'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `each'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `require'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler.rb:128:in `require'
/Users/idlecool/Workspace/Projects/hackerrank/config/application.rb:7:in `<top (required)>'
/Users/idlecool/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/Users/idlecool/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/Users/idlecool/Workspace/Projects/hackerrank/Rakefile:5:in `<top (required)>'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.3/lib/rake/rake_module.rb:25:in `load'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.3/lib/rake/rake_module.rb:25:in `load_rakefile'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.3/lib/rake/application.rb:583:in `raw_load_rakefile'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.3/lib/rake/application.rb:89:in `block in load_rakefile'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.3/lib/rake/application.rb:88:in `load_rakefile'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.3/lib/rake/application.rb:72:in `block in run'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.3/lib/rake/application.rb:70:in `run'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.3/bin/rake:33:in `<top (required)>'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/bin/rake:23:in `load'
/Users/idlecool/.rvm/gems/ruby-1.9.3-p194/bin/rake:23:in `<main>'
```
